- name: Install Kibana
  apt:
    name: kibana
    state: latest

- name: Add server ip
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: 'server.host:'
    line: 'server.host: ubuntuserver1'
    state: present

- name: Add elasticsearch ip
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: 'elasticsearch.hosts:'
    line: 'elasticsearch.hosts: ["http://ubuntuserver1:9200"]'
    state: present

- name: Restart Kibana
  systemd:
    state: restarted
    name: kibana
