- name: Install Kibana
  apt:
    name: kibana
    state: latest

- name: Add server ip
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: 'server.host:'
    line: 'server.host: 0.0.0.0'
    state: present

- name: Add elasticsearch ip
  lineinfile:
    path: /etc/kibana/kibana.yml
    regexp: 'elasticsearch.hosts:'
    line: 'elasticsearch.hosts: ["http://0.0.0.0:9200"]'
    state: present

- name: Restart Kibana
  systemd:
    state: restarted
    name: kibana
