- name: Install dependencies
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    update_cache: yes

- name: Add Docker key
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
    state: present

- name: Install Docker Engine
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    state: latest
    update_cache: yes

- name: Add group
  group:
    name: docker
    state: present

- name: Install $USER to docker group
  shell:
    cmd: usermod -aG docker $USER

- name: Install Docker compose
  shell:
    cmd: curl -L https://github.com/docker/compose/releases/download/1.25.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose

- name: Add permission +x to /usr/local/bin/docker-compose
  file:
    path: /usr/local/bin/docker-compose
    mode: +x
