- name: Add Elasticsearch key
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

- name: Add Elasticsearch repositor
  apt_repository:
    repo: deb https://artifacts.elastic.co/packages/6.x/apt stable main
    state: present

- name: Install beats
  apt:
    pkg:
    - filebeat
    - metricbeat
    update_cache: yes

- name: Enable inputs - filebeats
  lineinfile:
    path: /etc/filebeat/filebeat.yml
    regexp: '  enabled: false'
    line: '  enabled: true'

- name: Edit kibana ip - filebeats
  lineinfile:
    path: /etc/filebeat/filebeat.yml
    regexp: '  #host: "localhost:5601"'
    line: '  host: "ubuntuserver1:5601"'

- name: Edit elasticsearch ip - filebeat
  shell:
    cmd: sed 's_localhost:9200_ubuntuserver1:9200_' /etc/filebeat/filebeat.yml > /etc/filebeat/filebeat2.yml

- name: Edit elasticsearch ip - filebeat (2)
  shell:
    cmd: mv /etc/filebeat/filebeat2.yml /etc/filebeat/filebeat.yml
